#!/bin/bash

if [[ $# -le 1 ]] ; then
    echo 'Error: missing arguments. Usage: ./launchservers [group_name] [num_servers]'
    exit 1
fi

for i in $(eval echo {1..$2}); do
    screen -dmS "$1$i" java -jar ScrunkServer.jar -n $1$i --tcp $((5000+i)) --udp $((6000+i))
done

echo 'Servers launched!'