#!/bin/bash

wget https://raw.githubusercontent.com/SleepyStudios/ScrunkTools/master/runserverupdate &&
chmod 755 runserverupdate &&
wget https://raw.githubusercontent.com/SleepyStudios/ScrunkTools/master/runbatchserverupdate &&
chmod 755 runbatchserverupdate &&
sudo yum install glibc.i686 libstdc++.i686 &&
wget http://media.steampowered.com/installer/steamcmd_linux.tar.gz &&
tar -xvzf steamcmd_linux.tar.gz &&
sudo yum install java-1.8.0 &&
sudo yum remove java-1.7.0-openjdk &&
./runserverupdate
